### ISSUE TITLE
Make project more modular

### ISSUE THREAD

**Issue by ericbottard** [ericbottard/spring-shell2#28]
In particular, legacy support should be optional

**Comment by camilojc** [comment]
👍 should we move to a multi-project model?

spring-shell2
--> api (Standard interfaces/annotations to be used by users)
--> core (Main implementation classes and standard subpackage)
--> shell1-adapter
--> jcommander-adapter

**Comment by ericbottard** [comment]
sounds good, even though I'm not sure "core" and "api" need / can be separate.

Also, a samples subproject would host the example commands that we currently have.

Let me know if you intend to work on this, as if you do, we need to make it quick obviously, given that it would create many conflicts with other PRs

**Comment by ericbottard** [comment]
Also pay attention to https://github.com/ericbottard/spring-shell2/issues/37

**Comment by camilojc** [comment]
Sounds good. Just submitted https://github.com/ericbottard/spring-shell2/pull/38  for initial review - lots of file moves and initial breakdown of the project into multiple subprojects.
