### ISSUE TITLE
Assert architectural soundness of packages

### ISSUE THREAD

**Issue by ericbottard** [ericbottard/spring-shell2#37]
(and ideally check continuously in CI).

Check that upper level packages never reference classes from inner packages, only the other way around

**Comment by camilojc** [comment]
Should we start by the Bootstrap class?

It is our main entry point, but it currently prescribes the StandardParameterResolver as the default one. 

How should we tackle this? Should we remove the ParameterResolver bean from the Bootstrap and make the StandardParameterResolver an @Component annotated class? (Similar to the LegacyParameterResolver).

**Comment by ericbottard** [comment]
That's ok.
Having a dependency from top-level to inner level is ok, it's the other way around that is often a design flaw. Moreover, direct compile-time dependency or `@Component(Scan)` dependency is the same problem (the latter being more subtle).
