### ISSUE TITLE
Completion of quoted values is broken

### ISSUE THREAD

**Issue by ericbottard** [ericbottard/spring-shell2#54]
ie 
- `foo --bar "some value <TAB>` emitting `"hello"` doesn't escape the quotes
- `foo --bar <TAB>` emitting `value with spaces` doesn't enclose in quotes

Arguably, this should be handled by jline

**Comment by camilojc** [comment]
> Arguably, this should be handled by jline

I was thinking a bit more about this part, and I'm in two minds. If we take the `foo --bar <TAB>` as the example, from JLine's perspective, they might not know if:

1. `value with spaces` is a single word completion, in which case it should be enclosed in quoted, or if,
1. `value with spaces` are the only 3 possible words that follow `foo --bar` and hence why it's being returned by the completer so JLine doesn't added the enclosing quotes (?)

So, from JLine's perspective they might not know what the intention is? (just guessing).

Again, in two minds about this at this stage :)

**Comment by camilojc** [comment]
In other news, regarding the space at the end after completion, I believe it has to do with the way our CompleterAdapter is creating the Candidate:

```java
new Candidate(	completion.value(),
	completion.displayText(),
	"Comp for parameter " + resolver.describe(methodParameter).toString(),
	resolver.describe(methodParameter).help(),
	null, null, true)
```

That true at the end signals to JLine that the candidate is complete and hence a space is added.

It might be up to the specific completion scenario that we might want true/false there? Couldn't recall the exact case you mentioned, but was reading about the Candidate object and stumbled upon this, so decided to comment it here before I forget about it (in case it helps).
